### PR TITLE
PDK update and fix EL7 acceptance tests

### PR DESCRIPTION
**Pull request by treydock**

### CODE REVIEW

**Comment by johrstrom** [comment]
Test failures look a lot like https://github.com/OSC/ondemand/actions/runs/3378091046/jobs/5607842419 what we had in OOD last week. I imagine puppet relies on systemd and I've had to patch it in OOD and ansible.

https://github.com/OSC/ondemand/pull/2354

**Comment by treydock** [comment]
That does look similar. I'll give that systemd hack a shot.  What's so confounding is I can't reproduce locally on my laptop using Docker and other modules I manage for other projects don't have this issue all using almost identical logic.

**Comment by johrstrom** [comment]
Yea IDK, I even had to patch ansible to use podman. I'd chalk at least some part of it up to the GH action's kernel/environment too. I feel like using `ubuntu-latest` actions may be hurting us.

**Comment by treydock** [comment]
OMG that worked.  Thank you @johrstrom , I was banging my head against a wall all day trying to figure out why this wasn't working and it's been killing me since it affects almost every Puppet module I manage which is numerous.  I'm still confounded why this doesn't affect other community projects using beaker and Docker based acceptance tests.

**Comment by johrstrom** [comment]
Nice! Yea I would have expected failures all across the internet, but it seems it was only us.

**Pull request merged**
